on:
  pull_request:
    branches: [ "main", "develop" ]
  # (Optional) Enable running workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  Build_App:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: oracle-actions/setup-java@v1
        with:
            website: oracle.com
            release: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # This is an action that checks out your repository onto the runner, allowing you to run
      # scripts or other actions against your code (such as build and test tools)
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build app
        run: ./gradlew assemble
