name: Build

on:
  pull_request:
    branches: [ "main", "develop" ]
  # (Optional) Enable running workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  EnvSetup:
    uses: ./.github/workflows/envSetup.yml
  App:
    name: App
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: ./gradlew assemble
