name: Detekt

on:
  pull_request:
    branches: [ "main", "develop" ]
  # (Optional) Enable running workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Scan:
    EnvSetup:
      uses: ./.github/workflows/envSetup.yml
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Detekt
        run: ./gradlew detekt