name: Detekt

on:
  pull_request:
    branches: [ "main", "develop" ]
  # (Optional) Enable running workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    # This is an action that checks out your repository onto the runner, allowing you to run
    # scripts or other actions against your code (such as build and test tools)
    - uses: actions/checkout@v3
    - run: ./gradlew detekt
