name: Ktlint

on:
  pull_request:
    branches: [ "main", "develop" ]
  # (Optional) Enable running workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  EnvSetup:
    uses: .github/workflows/envSetup.yml
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Run Ktlint
        run: ./gradlew ktlintCheck